# Generated by Django 5.2.6 on 2025-09-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_insertar_paquetes_y_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_nombre',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.cliente'),
        ),
    ]
