# Generated by Django 5.2.6 on 2025-10-02 08:11

import django.db.models.deletion
import django.utils.timezone
import estructura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_remove_reserva_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=estructura.models.default_fecha),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.paquete'),
        ),
    ]
