# Generated by Django 4.1.3 on 2025-06-17 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_eventofotografico_imagenevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
