# Generated by Django 5.2.6 on 2025-10-02 08:33

import estructura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_alter_reserva_fecha_alter_reserva_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='limite_pago',
            field=models.DateTimeField(default=estructura.models.obtener_limite_pago),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
