# Generated by Django 4.1.3 on 2025-07-02 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_reserva_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.paquete'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_evento',
            field=models.CharField(choices=[('boda', 'Boda'), ('quince', 'Quince años'), ('grado', 'Grado'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
