# Generated by Django 5.2.6 on 2025-10-02 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_reserva_limite_pago_reserva_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
