# Generated by Django 4.1.3 on 2025-07-10 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_remove_reserva_fecha_reserva_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 18, 55, 24, 426023, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.paquete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_evento',
            field=models.CharField(choices=[('boda', 'Boda'), ('quince', 'Quinceañera'), ('bautizo', 'Bautizo'), ('comunion', 'Primera Comunión'), ('graduacion', 'Graduación'), ('cumpleanos', 'Cumpleaños'), ('empresarial', 'Evento Empresarial'), ('otros', 'Otros')], max_length=20),
        ),
    ]
