# Generated by Django 5.2.6 on 2025-09-30 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_remove_reserva_servicio_reserva_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
