# Generated by Django 5.2.6 on 2025-09-30 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0009_insert_paquetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('boda', 'Boda'), ('retrato', 'Retrato'), ('empresarial', 'Empresarial')], default='retrato', max_length=50),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_de_servicio',
            field=models.CharField(max_length=100),
        ),
    ]
