# Generated by Django 5.2.6 on 2025-09-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0011_insert_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_nombre',
            field=models.CharField(default='Individuo1', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.servicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10),
        ),
    ]
